spring:
  application:
    name: Spring Cloud Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com
          username: username
          password: password
          skipSslValidation: true
          search-paths:
            - "{profile}"
  security:
    user:
      name: kanggara75
      password: mockPassword
