name: Maven Build and Publish

on:
  push:
    branches:
      - main

jobs:
  mavenTest:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Maven Test
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/test/mvn@v0.1.3
  mavenbuild:
    runs-on: ubuntu-24.04
    needs: mavenTest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Build Maven
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/mavenbuild@v0.1.3
        with:
          application-properties: ${{ secrets.APPLICATION_PROPERTIES }}
  dockerBuild:
    runs-on: ubuntu-24.04
    needs: mavenbuild
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Build and Push to Docker Hub
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: target/
      - uses: KAnggara/DevOps/dockerbuild@feature-dockerBuild
        with:
          registry: docker.io
          image_name: kanggara75/scc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}